npmAlwaysAuth: false

npmAuthToken: "${NPM_AUTH_TOKEN-must_supply_this_value_in_zshrc}"

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@fullhuman/postcss-purgecss@*":
    dependencies:
      postcss: ^8.2.10
  "@graphql-codegen/plugin-helpers@*":
    dependencies:
      graphql: ^14.6.0
  "@graphql-tools/links@6.2.1":
    dependencies:
      subscriptions-transport-ws: ^0.9.18
  "@octokit/rest@16.43.2":
    dependencies:
      "@octokit/core": ^3.3.0
      graphql: ^14.6.0
      subscriptions-transport-ws: ^0.9.18
  codemirror-graphql@*:
    dependencies:
      graphql-language-service-utils: ^2.4.4
  create-react-class@*:
    dependencies:
      react: ^16.13.0
  express-graphql@*:
    dependencies:
      graphql: ^14.6.0
  graphiql@*:
    dependencies:
      prop-types: ^15.7.2
  next@9.4.2:
    dependencies:
      typescript: ^4.0.3
  react-beautiful-dnd@*:
    peerDependencies:
      react-dom: ^16.13.0
  react-dismissible@*:
    peerDependencies:
      react: ^16.13.0
  tsup@*:
    dependencies:
      typescript: ^4.0.3

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-sources.cjs
